datadog:
  site: "datadoghq.com"
  apiKey: ************
  appKeyExistingSecret: null
  appKey: ************
  apiKeyExistingSecret: null
  kubelet:
    host:
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    hostCAPath: null
    tlsVerify: false
  tags:
    - "env:devopsdev"
  apm:
    portEnabled: true    helm list

# -----------------------------------------------------------------------------
# Cluster Agent configuration
# -----------------------------------------------------------------------------
clusterAgent:
  enabled: true  # (MANDATORY) Set to true to deploy the Datadog Cluster Agent.
  metricsProvider:
    enabled: true  # (MANDATORY) Enables the external metrics provider for HPA and custom metrics.
    useDatadogMetrics: true  # (MANDATORY) Use DatadogMetrics CRD for advanced metric routing.
  # Optionally, you can configure additional features such as admission controller, cluster checks, etc.

providers:
  aks:
    enabled: true
  admissionController:
    enabled: false
